train: "../training/mask*.png"
valid: "../testing/mask*.png"
log: "logs"
logging_step: 100
validation_interval: 2000 # Save and valid have same interval
checkpoints: "checkpoints"

batch_size: 2
lr: 0.001
RESNET_PLUS_PLUS: True
IMAGE_SIZE: 1600
CROP_SIZE: 224